export const players = [
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p3",
    name: "Giocatore 3",
    number: 3,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p4",
    name: "Giocatore 4",
    number: 4,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p5",
    name: "Giocatore 5",
    number: 5,
    role: "Portiere",
    photo: "/players/p5.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p6",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p1",
    name: "Giocatore 1",
    number: 1,
    role: "Portiere",
    photo: "/players/p1.jpg",
    // --- MODIFICA QUI PER QUESTO GIOCATORE ---
    altezza: "190cm",
    peso: "85kg",
    piede: "Destro",
    eta: 24,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
  {
    id: "p2",
    name: "Giocatore 2",
    number: 2,
    role: "Difensore",
    photo: "/players/p2.jpg",
    altezza: "182cm",
    peso: "78kg",
    piede: "Destro",
    eta: 22,
    presenze: 0,
    gol: 0,
    assist: 0,
    minuti: 0,
  },
];

export const staff = [
  { id: "s1", name: "Mister 1", role: "Allenatore", photo: "/players/mister1.jpg" },
  { id: "s2", name: "Mister 2", role: "Vice Allenatore", photo: "/players/mister2.jpg" },
];
