/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFanwallRouteImport } from './routes/api/fanwall'
import { Route as ApiMvpRouteImport } from './routes/api/mvp'
import { Route as ApiPredictionsRouteImport } from './routes/api/predictions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFanwallRoute = ApiFanwallRouteImport.update({
  id: '/api/fanwall',
  path: '/api/fanwall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMvpRoute = ApiMvpRouteImport.update({
  id: '/api/mvp',
  path: '/api/mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsRoute = ApiPredictionsRouteImport.update({
  id: '/api/predictions',
  path: '/api/predictions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/fanwall': typeof ApiFanwallRoute
  '/api/mvp': typeof ApiMvpRoute
  '/api/predictions': typeof ApiPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/fanwall': typeof ApiFanwallRoute
  '/api/mvp': typeof ApiMvpRoute
  '/api/predictions': typeof ApiPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/fanwall': typeof ApiFanwallRoute
  '/api/mvp': typeof ApiMvpRoute
  '/api/predictions': typeof ApiPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/fanwall' | '/api/mvp' | '/api/predictions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/fanwall' | '/api/mvp' | '/api/predictions'
  id: '__root__' | '/' | '/api/fanwall' | '/api/mvp' | '/api/predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFanwallRoute: typeof ApiFanwallRoute
  ApiMvpRoute: typeof ApiMvpRoute
  ApiPredictionsRoute: typeof ApiPredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fanwall': {
      id: '/api/fanwall'
      path: '/api/fanwall'
      fullPath: '/api/fanwall'
      preLoaderRoute: typeof ApiFanwallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mvp': {
      id: '/api/mvp'
      path: '/api/mvp'
      fullPath: '/api/mvp'
      preLoaderRoute: typeof ApiMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions': {
      id: '/api/predictions'
      path: '/api/predictions'
      fullPath: '/api/predictions'
      preLoaderRoute: typeof ApiPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFanwallRoute: ApiFanwallRoute,
  ApiMvpRoute: ApiMvpRoute,
  ApiPredictionsRoute: ApiPredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
